export const StorageKeys = {
    CURRENT_MENU: '@CURRENT_MENU',
    USER: '@USER'
}

export const MenuStates = {
    POSTS: 'POSTS',
    USUARIOS: 'USUARIOS',
    EDIT_PROFILE: 'EDIT_PROFILE',
    HASH: 'HASH',
    SECURITY_CONFIG: 'SECURITY_CONFIG',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD'
}