spring:
  datasource:
    url: jdbc:postgresql://172.45.45.10:5432/postgres
    username: postgres
    password: Postgres123
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
  config: classpath:logback.xml
